### ISSUE TITLE
Class 'PhpTabs\Reader\Midi\TabString' not found

### ISSUE THREAD

**Issue by KyleHin** [stdtabs/phptabs#10]
Hi, i get the above error when trying to parse Midi file via
$tab = new PhpTabs(public_path("midi/".$filename));
error is at
stdtabs\phptabs\src\PhpTabs\Reader\Midi\MidiReader.php
* Create percussion strings
   * 
   * @param  int $stringCount
   * @return array
   */
  private function createPercussionStrings($stringCount)
  {
    $strings = array();
 
    for ($i = 1; $i <= $stringCount; $i++) {
      $strings[] = new TabString($i, 0);
    }
 
    return $strings;
  }

may i know what exactly is TabString? thank you

**Comment by landrok** [comment]
Hi,

As of *String* is a PHP reserved keyword, [TabString](https://github.com/stdtabs/phptabs/blob/master/src/PhpTabs/Music/TabString.php) represents a **Guitar string**.

This error should not happen as MidiReader has been patched in dev-master branch. Nevertheless, this was not packaged into 0.5 release and previous. This is now done with current release 0.6.0.

Could you please make an update and confirm that the MIDI parsing process is working?

**Comment by KyleHin** [comment]
Hi, im sorry for the super late response. I will update to latest version and try again. Thx!

**Comment by KyleHin** [comment]
Hi, i have tested and works like a charm now. thx lot.
