### ISSUE TITLE
Tab from scratch

### ISSUE THREAD

**Issue by csguth** [stdtabs/phptabs#12]
First of all, thank you for your Library! Very nice job, mate!!

I'm working on a proprietary tablature format and I'd like to convert it to phptabs format, in order to export to midi and gp5. I already mapped some of the structures like Channel, Note, Voice, Measure but the save function is still throwing errors. I'm probably missing something. So I'd like to ask if you have a minimal example of a tablature written from scratch. That would be very useful!

Thanks again.

Regards,
Chrystian.

**Comment by landrok** [comment]
Hi Chrystian,

Creating a song from scratch is one of the most exciting features of Phptabs. Sadly, it's not well-documented. 

So, I wrote a dedicated manual (with examples) to [create a song from scratch](https://stdtabs.github.io/create-a-tablature-from-scratch.html).

Based on your returns, I would evolve this document if necessary.

Thanks for using PhpTabs.

**Comment by MrChros** [comment]
Hello,
I also would like to say thank you for this library. It's a great tool and and basically works very well. :)

So far, I was only reading information from gp5-files. Now, I started to create own tablatures. Unfortunately, so far I wasn't able to create an tablature and export is as gp5-file or midi-file.

I used the example from this website: https://stdtabs.github.io/create-a-tablature-from-scratch.html (A minimal and working tablature)

See my code here:
![image](https://user-images.githubusercontent.com/41364016/57156338-fe1ca180-6ddd-11e9-8254-bba4c9f42bf0.png)


This is the answer I get, when I run this code:
![image](https://user-images.githubusercontent.com/41364016/57156380-20162400-6dde-11e9-8498-3913fd818977.png)


Any idea, what I did wrong? I had the thought, that I did not install PhpTabs corretly. But reading gp5-files works flawlessly. I'd be grateful for any tips where to debug or what to try. If I'll find a solution I'll contribute.

Best regards,

Chros

**Comment by MrChros** [comment]
Ok, so the "Song is empty" message was issued, because no MeasureHeader was added to the tablature.
See snippit from SongBase.php:
![image](https://user-images.githubusercontent.com/41364016/57161844-d6810580-6dec-11e9-9e41-190866d365d2.png)

Adding line 126 in the following snippit solved this issue:
![image](https://user-images.githubusercontent.com/41364016/57161958-2790f980-6ded-11e9-80a7-8454fa9a562f.png)

Output looks now like this:
![image](https://user-images.githubusercontent.com/41364016/57161987-3d9eba00-6ded-11e9-99d1-202ce6fb4be9.png)

Unfortunately, it is not possible to open the exportet gp5-file with Guitar Pro 5. When opening the following error message occures:
![image](https://user-images.githubusercontent.com/41364016/57162052-6fb01c00-6ded-11e9-8dbf-ba6b6e993f1f.png)
Well, even if the error message is in french (I guess), it shows some memory addresses within the GP5.exe. At this point, I'm not sure how to debug further.... :(

**Comment by landrok** [comment]
Hi MrChros,

Could you please provide your PHP and PhpTabs version?

```php
echo $tablature->getVersion();
```

Your PhpTabs version seems to be older than this https://github.com/stdtabs/phptabs/commit/6bee9800ad4cd06778e81d1df340a099322921e4 that fixed this dependency failure and was packaged with PhpTabs 0.6.1. Previously, an empty Song was attached instead of the current one.

Other errors, including memory violation, are "normal" for this inconsistent state.

FYI PhpTabs 0.6.1 requires PHP7+

Thanks for using PhpTabs.

**Comment by MrChros** [comment]
Hi landrok,

thank for coming back to me so quickly. I'm using the following versions:
![image](https://user-images.githubusercontent.com/41364016/57191070-bacb4b80-6f21-11e9-8c88-0ff027c8f42e.png)

My code hasn't changed (except output of versions).
In my first post, I did not follow your manual correctly. This is why I had the correct issued error message in the first place.

Currently, I run the code an a local XAMPP server, installed about two weeks ago. So it is pretty up-to-date, I guess.

Thanks and have a good one!

**Comment by landrok** [comment]
Your versions are ok. My bad, I've answered with your first post in mind.

Examples were not enough as is to generate a readable gp5 file (out of PhpTabs), some more attributes must be initialized to avoid memory violation errors.

For some, there are new commits on the master branch (`composer update`) and for the others, the examples have been updated at https://stdtabs.github.io/create-a-tablature-from-scratch.html.

Could you take a look and confirm that it works?

**Comment by MrChros** [comment]
Hey landrok,

great work! The library manual seem to work! See my code here:
![image](https://user-images.githubusercontent.com/41364016/57466301-a61fe800-7280-11e9-8ccd-88f23779d27d.png)

I basically copied the code from your manual, just added a custom tempo for the single MeasureHeader.
I'm going to play with PhpTabs a bit and create longer tabs  from scratch. I'll post the results the next days.

Unfortunately, the exported MIDI file seem not to be OK nor valid. I did an export as MIDI from the Guitar Pro 5 file. I don't know if it helps, but here is a diff view of the two MIDI files:
![image](https://user-images.githubusercontent.com/41364016/57466611-4c6bed80-7281-11e9-93ce-843daf6d2c60.png)

Please let me know, if I can do or try anything else. :)

**Comment by MrChros** [comment]
Good news! I did work a bit with PhpTabs and merged multiple self written tabs into a single tablature using this library. Doing this, I'm only interested in the tempo and time signature of each measure.

The export as gp5-file works beautifully. :)
The export as MIDI file is the same as before.

Good job, I really enjoy PhpTabs!

**Comment by landrok** [comment]
Hi @csguth @MrChros 

Sorry for not having answered your questions before.

I've released PhpTabs 0.6.3 which should fix this problem. MIDI timing may be improved for complex tablatures, it's a work in progress.

Can you test it and reopen if needed ?

**Comment by MrChros** [comment]
Hi @landrok,

thanks for the update.
I'll check the MIDI export function within this week and provide feedback. 👍 

Best,
MeChros

**Comment by MrChros** [comment]
Hi @landrok,

I did some first quick tests. Mainly I used the code from my post from 9th of May last year. This code creates a complete new tab in with the PhpTabs library and peforms exports as gp5- and MIDI-file.

When running the gp5-export I receive an error message:
![image](https://user-images.githubusercontent.com/41364016/97171373-a5895300-178d-11eb-92ce-4430306f9d6f.png)

The export to MIDI seems to work. I can import the file into Guitar Pro 5 and other Audio-Softwares. Nonetheless there is one thing I cannot explain. With the script (see ZIP file below) I add three measures to the track. Each measure has a different time signature and different tempo. The importet MIDI file in Guitar Pro does not show these three measures. But I may be a proboem with my code as well.


Here is the ZIP file:
[test.zip](https://github.com/stdtabs/phptabs/files/5438737/test.zip)

**Comment by landrok** [comment]
Your code is OK. From scratch features are not well tested.

So, I wrote a patch that is packaged with 0.6.4 release. 

I included your code in the [test suite](https://github.com/stdtabs/phptabs/blob/master/test/PhpTabs/TabsFromScratchTest.php) to enforce QA.

A little advise for your code, you don't need all imports, I commented in the code below the useless ones.

```php
use PhpTabs\PhpTabs;

// use PhpTabs\Music\Song;
// use PhpTabs\Music\SongBase;
use PhpTabs\Music\Tempo;
use PhpTabs\Music\Track;
use PhpTabs\Music\Marker;
use PhpTabs\Music\Channel;
use PhpTabs\Music\Measure;
use PhpTabs\Music\Duration;
use PhpTabs\Music\TabString;
use PhpTabs\Music\TimeSignature;
use PhpTabs\Music\MeasureHeader;

// use PhpTabs\Component\Config;
// use PhpTabs\Component\Tablature;
```
Tablature, Song and SongBase are just intermediate models that are created with PhpTabs instanciation.

**MIDI issue**

MIDI writer needs some more work. I am not satisfied with the current implementation. First, let's say it's an alpha version as it does not generate corrupted files anymore :) Time management has to be improved.

Big thanks for your fast feedback !

**Comment by MrChros** [comment]
Thank for the advise about imports. :)
If there is anything I can help with, I'm happy to do so.

Just FYI:
My friends and myself are using PhpTabs on a regular basis. We use it within a self-created web-repository for our tabs. It allows us to see the differences and changes from version to version of song. :)

It is good work you are doing there!
