### ISSUE TITLE
Render option for single measures only

### ISSUE THREAD

**Issue by MrChros** [stdtabs/phptabs#14]
I have recently tried the render function to ASCII format. It work very well, but I did not see an option to render only a single measure or a range of measures of a single track.

In order to enable such a feature I wrote an external function:
```php
function PhpTabs_Render_Single_Measure(\PhpTabs\PhpTabs $tab_source, $track_number, $measure_number)
{
	// Create new Tablature, Track and copy Track name
	$tablature 	= new PhpTabs();
	$track 		= new Track();
	$track->setName($tab_source->getTrack($track_number)->getName());
	$tablature->addTrack($track);

	// Copy Strings
	$strings = $tab_source->getTrack($track_number)->getStrings();
	for($i=0;$i<count($strings);$i++) {
		$s = new TabString();
		$s->copyFrom($strings[$i]);
		$track->addString($s);
	}

	// Copy Measure Header according to $measure_number
	$mh = new MeasureHeader();
	$mh->copyFrom($tab_source->getMeasureHeader($measure_number));
	$mh->setNumber(1);
	$tablature->addMeasureHeader($mh);

	// Copy Measure according to $measure_number
	$m = new Measure($mh);
	$m->copyFrom($tab_source->getTrack($track_number)->getMeasure($measure_number));
	$track->addMeasure($m);

	
	$render_output = $tablature->getRenderer('ascii')->render(0);
	while($render_output[0] == chr(13) || $render_output[0] == chr(10))
	{
		$render_output = ltrim($render_output, chr(10));
		$render_output = ltrim($render_output, chr(13));
	}

	$output = "Measure " . ($measure_number + 1);
	$output.= " (" . $mh->getTimeSignature()->getNumerator() . "/" . $mh->getTimeSignature()->getDenominator()->getValue() . "):";
	$output.= "\n";
	$output.= $render_output;

	return $output;
}
```

I"m sure there is a better/easier way to do that. But for the time being, this function works and could easily be extended to render a range of measures.

For future version, I suggest to add this feature to the renderer. :)

Best,

MrChros

**Comment by landrok** [comment]
PhpTabs version 1.0.0 has been released. It 's packaged with such features.

Instead of doing this kind of slices in the render methods, slicing and targeting are now parts of the core.

You may have a look at [slicing](https://phptabs.readthedocs.io/en/latest/slice-tracks-measures.html) or [targeting](https://phptabs.readthedocs.io/en/latest/target-track-measure.html) manuals.

[Renderers](https://phptabs.readthedocs.io/en/latest/render.songs.html) have been simplified as they do not receive a track index anymore.

2 quick examples for rendering below.

- Target and render a single measure in one track

```php
use PhpTabs\PhpTabs;

$song = new PhpTabs('my-song.gp5');

echo $song->onlyTrack(0)->onlyMeasure(0)->toAscii();

```

- Slice and render 1st and 2nd measures in one track

```php
use PhpTabs\PhpTabs;

$song = new PhpTabs('my-song.gp5');

echo $song->onlyTrack(0)->sliceMeasure(0, 1)->toAscii();

```

Making that in the core extends this slicing features to every other ways.

- Slicing and saving the results as a new gp5 file in one line of code

```php
use PhpTabs\IOFactory;

IOFactory()->fromFile('my-song.gp5')->onlyTrack(0)->save(first-track-my-song.gp5');

```

If you want to see all changes in this release, please see the [changelog](https://github.com/stdtabs/phptabs/blob/master/CHANGELOG.md) and the [new manual](https://phptabs.readthedocs.io/) 

So, now you may target single and ranges of tracks and measures :)

Thanks for your work and I hope this helps !

**Comment by MrChros** [comment]
Hi landrok,
thanks for the update. I'm going to try the new functions within the next one or two weeks.
I'll post my feedback then. :)

Best,
Chros

**Comment by MrChros** [comment]
Hello landrok,
I just downloaded the newest version (1.0.1). When running an old test with the new library I receive the new error message:
`php
Fatal error: Uncaught TypeError: Argument 1 passed to PhpTabs\Music\DivisionType::convertTime() must be of the type int, float given, called in C:\xampp\htdocs\tab_render\PhpTabs\Music\Duration.php on line 83 and defined in C:\xampp\htdocs\tab_render\PhpTabs\Music\DivisionType.php:44 Stack trace: #0 C:\xampp\htdocs\tab_render\PhpTabs\Music\Duration.php(83): PhpTabs\Music\DivisionType->convertTime(1920) #1 C:\xampp\htdocs\tab_render\PhpTabs\Reader\GuitarPro\Helper\GuitarPro5Beat.php(76): PhpTabs\Music\Duration->getTime() #2 C:\xampp\htdocs\tab_render\PhpTabs\Reader\GuitarPro\Helper\GuitarPro5Measure.php(30): PhpTabs\Reader\GuitarPro\Helper\GuitarPro5Beat->readBeat(960, Object(PhpTabs\Music\Measure), Object(PhpTabs\Music\Track), Object(PhpTabs\Music\Tempo), 0) #3 C:\xampp\htdocs\tab_render\PhpTabs\Reader\GuitarPro\Helper\GuitarPro5Measures.php(39): PhpTabs\Reader\GuitarPro\Helper\GuitarPro5Measure->readMeasure(Object(PhpTabs\Music\Measure), Object(PhpTabs\Music\Track), Object(PhpTabs\Music\Tempo)) #4 C:\xampp\htdocs\tab_ren in C:\xampp\htdocs\tab_render\PhpTabs\Music\DivisionType.php on line 44`

I hope this helps somehow....

Best,
Chros

**Comment by landrok** [comment]
Hello MrChros,
maybe I'm wrong but I think you may have downloaded from the master branch which has been broken today. I'm currently working on stricter types in the Music models.

To be sure of it, you may check the first lines of `C:\xampp\htdocs\tab_render\PhpTabs\Music\Duration.php`.
That is the case if you have something like :
```php
<?php

declare(strict_types = 1);
```

Then you should download a more stable release https://github.com/stdtabs/phptabs/releases/tag/1.0.1 or with a composer installation.

Hope this helps,
landrok

**Comment by MrChros** [comment]
Hello landrok,
by downloading the version from the link you posted, everything worked with rendering! 
I think the method is quite easy to understand and to use after having a look an the manual page.

Thank you for your support and effort on this library!

Best regards,
Chros
