### ISSUE TITLE
Great feature $tabs->getRenderer('vextab')->render($ctrack);

### ISSUE THREAD

**Issue by ghost** [stdtabs/phptabs#2]
With small tweaks is getting along pretty well.

http://fretsolo.com/index.php?play3=]/Amon-Amarth/Amon_Amarth-Gods_Of_War_Arise.gp5&track=0
Thx.

**Comment by landrok** [comment]
Thank you for using PhpTabs

I have tested fretsolo website and if I may, here are some suggestions:

- use a try catch structure for making renderer calls (In case, track parameter is not valid)
- it could be more secure to block directory listing (Apache)
- If you want a faster parsing, you should use PHP7 (next PhpTabs release will implement a cache)
- a backlink to the PhpTabs project would be greatly appreciated 😃
