### ISSUE TITLE
duration of file

### ISSUE THREAD

**Issue by Gemorroj** [stdtabs/phptabs#20]
Hi. I try to use the library to get info about midi files.
How I can get duration of file?
For example, the duration of [this](https://github.com/stdtabs/phptabs/files/6526412/5fdf1a8eba032986038158.zip) file is `5:52`

I saw the tutorial https://phptabs.readthedocs.io/en/latest/examples/ex.calculate-measure-and-beat-durations-in-seconds.html but it something strange for me. Because the resulted duration so small, or so big when I tried summarize all beats/voices.
Sorry, I'm not a musician)

**Comment by landrok** [comment]
Hi @Gemorroj 

The given examples only calculate duration for one measure or one beat.

Below, here is an example for the whole song.

```php
use PhpTabs\PhpTabs;

$filename = 'song.mid';

$song  = new PhpTabs($filename);
$total = 0;


// Take all measures for the first track
$measures = $song->getTrack(0)->getMeasures();

// Sum durations for each measure
foreach ($measures as $measure) {

    // Calculate duration in seconds
    $total += 60
        * $measure->getTimeSignature()->getNumerator()
        / $measure->getTempo()->getValue();

}

// Print duration
echo sprintf("Duration=%ss", $total);

```

And the result :

```sh
Duration=352s
```

Hope this helps.
landrok

**Comment by Gemorroj** [comment]
@landrok thanks! it works
