### ISSUE TITLE
I have problem to convert measure length to seconds. please help!

### ISSUE THREAD

**Issue by motniemtin** [stdtabs/phptabs#3]
{
        "header": {
          "number": 1,
          "start": 960,
          "length": 3840,
          "timeSignature": {
            "numerator": 4,
            "denominator": {
              "value": 4,
              "dotted": false,
              "doubleDotted": false,
              "divisionType": {
                "enters": 1,
                "times": 1
              }
            }
          },
          "tempo": 120,
          "marker": null,
          "repeatOpen": false,
          "repeatAlternative": 0,
          "repeatClose": 0,
          "tripletFeel": 1
        }
      }
What time spend for this measure ?, how to calculate ?

**Comment by landrok** [comment]
Hi,

To calculate duration in seconds, the formula is  `(Number of beats) * 60 / Tempo`

In your case, it's `4 * 60 / 120 = 2s`

An example with PhpTabs:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use PhpTabs\PhpTabs;

// Instanciate a tablature
$tablature = new PhpTabs(
	__DIR__ . "/vendor/stdtabs/phptabs/test/PhpTabs/samples/testSimpleTab.gp3"
);

// Take a measure
$measure = $tablature->getTrack(0)->getMeasure(0);

// Calculate duration in seconds
$duration = 60 
	* $measure->getTimeSignature()->getNumerator()
	/ $measure->getTempo()->getValue();

// Print duration
echo sprintf("Duration=%ss", $duration);
```

Hope this helps.

**Comment by motniemtin** [comment]
I got it!, many thanks..

**Comment by landrok** [comment]
This example has been integrated to this [tutorial](https://stdtabs.github.io/calculate-measure-and-beat-durations-in-seconds.html#measure-duration).

Thanks you for using PhpTabs :)
