### ISSUE TITLE
Error when convert gp5 to midi

### ISSUE THREAD

**Issue by motniemtin** [stdtabs/phptabs#4]
Fatal error: Uncaught TypeError: Argument 1 passed to PhpTabs\Writer\Midi\MidiWriter::__construct() must be an instance of PhpTabs\Model\Song, instance of PhpTabs\Music\Song given, called in /src/PhpTabs/Component/Writer.php on line 60 and defined in /src/PhpTabs/Writer/Midi/MidiWriter.php:37 Stack trace: #0 /src/PhpTabs/Component/Writer.php(60): PhpTabs\Writer\Midi\MidiWriter->__construct(Object(PhpTabs\Music\Song)) #1 /src/PhpTabs/Component/Tablature.php(212): PhpTabs\Component\Writer->build('midi') #2 /src/PhpTabs/PhpTabs.php(138): PhpTabs\Component\Tablature->convert('midi') #3 /index.php(8): PhpTabs\PhpTabs->__call('conver in /src/PhpTabs/Writer/Midi/MidiWriter.php on line 37

**Comment by landrok** [comment]
Nice catch!

This [commit](https://github.com/stdtabs/phptabs/commit/a893ab02ee7b7fcfcca0fb3d5544a9a6d2355e43) should fix this issue.

MidiWriter is being rewritten and is considered as an (the most) experimental feature.

**Comment by motniemtin** [comment]
Thank you so much, well done men!

**Comment by motniemtin** [comment]
I have new error, problem when convert midi..


Fatal error: Uncaught Error: Class 'PhpTabs\Writer\Midi\Velocities' not found in /Guitar/phptabs-master/src/PhpTabs/Writer/Midi/MidiSequenceParser.php:643 Stack trace: #0 /Guitar/phptabs-master/src/PhpTabs/Writer/Midi/MidiSequenceParser.php(264): PhpTabs\Writer\Midi\MidiSequenceParser->getRealVelocity(Object(PhpTabs\Writer\Midi\MidiSequenceHelper), Object(PhpTabs\Music\Note), Object(PhpTabs\Music\Track), Object(PhpTabs\Music\Channel), 4, 7) #1 /Guitar/phptabs-master/src/PhpTabs/Writer/Midi/MidiSequenceParser.php(231): PhpTabs\Writer\Midi\MidiSequenceParser->makeNotes(Object(PhpTabs\Writer\Midi\MidiSequenceHelper), Object(PhpTabs\Music\Channel), Object(PhpTabs\Music\Track), Object(PhpTabs\Music\Beat), Object(PhpTabs\Music\Tempo), 4, 7, 0, Array) #2 /Guitar/phptabs-master/src/PhpTabs/Writer/Midi/MidiSequenceParser.php(201): PhpTabs\Writer\Midi\MidiSequenceParser->makeBeats(Object(PhpTabs\Writer\Midi\MidiSequenceHe in /Guitar/phptabs-master/src/PhpTabs/Writer/Midi/MidiSequenceParser.php on line 643


Maybe you have "use PhpTabs\Music\Velocities;" on MidiSequenceParser.php

**Comment by landrok** [comment]
Nice catch, fixed by [this commit](https://github.com/stdtabs/phptabs/commit/1936678b76c5dec8ec149b54a3fab08d14762c03)

**Comment by landrok** [comment]
Duplicate with #6
