### ISSUE TITLE
Could you add capo fret parser to your class?

### ISSUE THREAD

**Issue by motniemtin** [stdtabs/phptabs#7]
I have good idea, I love it. But may be your didn't parse capo fret data from gp file, I hop you add it

**Comment by landrok** [comment]
Good idea, you can achieve that with ```Track::getOffset()``` method.


An example with PhpTabs, the 2nd track has a capo:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use PhpTabs\PhpTabs;

// Instanciate a tablature
$tablature = new PhpTabs(
	__DIR__ . "/vendor/stdtabs/phptabs/test/PhpTabs/samples/testSimpleTab.gp5"
);

// Take the 2nd track
$track = $tablature->getTrack(1);

// Get offset position (capo)
$offset = $track->getOffset();

// Print offset
echo sprintf("offset=%s", $offset);
```

will output ```offset=1```

**Comment by motniemtin** [comment]
Thank so much, i hope that you will support gp, gpx file in next time..

**Comment by landrok** [comment]
You're welcome!
For other questions/demands, could you open a new issue please? This would be better for discussing and planning new features.
